// currencySlice.js
import { createSlice } from '@reduxjs/toolkit';

// Define initial state
const initialState = {
    images: [], // Default currency
};

// Create the slice
const sketchSlice = createSlice({
    name: 'sketch', // Name of the slice
    initialState: initialState,
    reducers: {
        // Set the selected currency
        setCapturedSketches: (state, action) => {
            
            const { key, url } = action.payload;

            // Check if the key already exists in the images array
            const existingIndex = state.images.findIndex(image => image.key === key);

            if (existingIndex !== -1) {
                // Replace the existing image if the key matches
                const updatedImages = [...state.images];
                updatedImages[existingIndex] = { key, url }; // Update the image with the new URL
                return {
                ...state,
                images: updatedImages
                };
            } else {
                // If key doesn't exist, add a new image to the array
                return {
                    ...state,
                    images: [...state.images, { key, url }]
                };
            }
        },
        removeCapturedSketches: (state, action) => {
            const { key } = action.payload;
            return {
                ...state,
                images: state.images.filter(i => i.key !== key)
            }
        },
        clearCapturedSketches: (state, action) => {
            return {
                ...state,
                images: []
            }
        }
    },
});

// Export actions automatically generated by createSlice
export const { setCapturedSketches, removeCapturedSketches, clearCapturedSketches } = sketchSlice.actions;

// Export the reducer to be included in the store
export default sketchSlice.reducer;
